### ISSUE TITLE
[Help] Using this

### ISSUE THREAD

**Issue by ItsEternity** [mindcat/MulticraftApi#1]
Hey, 

I'm not familiar with the Multicraft API, so I thought I'd request some help. If I were to send a console command via Python (using a web server and want to send a command), how would I do this? (Let's say the command is /give * steak). 

Also, where do I put my Multicraft API key?

**Comment by mindcat** [comment]
@ItsEternity (I am live)

**Comment by mindcat** [comment]
@ItsEternity using my multicraftapi should be easy.
but I don't know which you means.
Terminal version:
```bash
╭─mindcat@mindcat-linux-pc ~/workspace/CCSheet  
╰─➤  python2 multicraftapi.py findServers -a name -a "444303908"
[API] [DEBUG] Key: '01ad4e8729f146c160b7["name"]["444303908"]findServersmindcat'
[API] [DEBUG] Params: OrderedDict([('field', '["name"]'), ('value', '["444303908"]'), ('_MulticraftAPIMethod', 'findServers'), ('_MulticraftAPIUser', 'mindcat'), ('_MulticraftAPIKey', '325087349e50e26c227ac23206318b23')])
[API] [DEBUG] Url: u'http://server5-temp.chinacraft.cc:998/api.php?field=%5B%22name%22%5D&value=%5B%22444303908%22%5D&_MulticraftAPIMethod=findServers&_MulticraftAPIUser=mindcat&_MulticraftAPIKey=325087349e50e26c227ac23206318b23'
{u'errors': [], u'data': {u'Servers': {u'1508': u'S5TMC04-444303908'}}, u'success': True}
{u'data': {u'Servers': {u'1508': u'S5TMC04-444303908'}},
 u'errors': [],
 u'success': True}
╭─mindcat@mindcat-linux-pc ~/workspace/CCSheet  
╰─➤  python2 multicraftapi.py createCommand                     
This method usage: 
('server_id', 'name', 'role', 'chat', 'response', 'run')
Traceback (most recent call last):
  File "multicraftapi.py", line 232, in <module>
    main()
  File "multicraftapi.py", line 225, in main
    pprint.pprint(api(method,*params))
  File "multicraftapi.py", line 136, in __call__
    raise TypeError("Not enough arguments. (%d < %d)%s" % (len(args),len(__method[func]),__method[func]))
TypeError: Not enough arguments. (0 < 6)('server_id', 'name', 'role', 'chat', 'response', 'run')
╭─mindcat@mindcat-linux-pc ~/workspace/CCSheet  
╰─➤  python2 multicraftapi.py sendConsoleCommand                                                                                                                 1 ↵
This method usage: 
('server_id', 'command')
Traceback (most recent call last):
  File "multicraftapi.py", line 232, in <module>
    main()
  File "multicraftapi.py", line 225, in main
    pprint.pprint(api(method,*params))
  File "multicraftapi.py", line 136, in __call__
    raise TypeError("Not enough arguments. (%d < %d)%s" % (len(args),len(__method[func]),__method[func]))
TypeError: Not enough arguments. (0 < 2)('server_id', 'command')
╭─mindcat@mindcat-linux-pc ~/workspace/CCSheet  
╰─➤  python2 multicraftapi.py sendConsoleCommand 1508 "/give mindcat steak"                                                                                      1 ↵
[API] [DEBUG] Key: '01ad4e8729f146c160b71508/give mindcat steaksendConsoleCommandmindcat'
[API] [DEBUG] Params: OrderedDict([('server_id', '1508'), ('command', '/give mindcat steak'), ('_MulticraftAPIMethod', 'sendConsoleCommand'), ('_MulticraftAPIUser', 'mindcat'), ('_MulticraftAPIKey', '072c1d8d7d49182fb9148acba8a0d108')])
[API] [DEBUG] Url: u'http://server5-temp.chinacraft.cc:998/api.php?server_id=1508&command=%2Fgive+mindcat+steak&_MulticraftAPIMethod=sendConsoleCommand&_MulticraftAPIUser=mindcat&_MulticraftAPIKey=072c1d8d7d49182fb9148acba8a0d108'
{u'data': [], u'errors': [], u'success': True}
╭─mindcat@mindcat-linux-pc ~/workspace/CCSheet  
╰─➤  
 ```
Python Version:
```
# Copyright (C) 2016 mindcat <mindcat@nekoheart.com>
#coding: utf8
import plyvel
import multicraftapi
import msgpack
import random, string
import logging as loo
import time
logging = loo
import HTMLParser
htmltool = HTMLParser.HTMLParser()

UNPACKPARAM = {
    "encoding": "utf-8"
}

CFGTABLE = [
 {'fee': '120', 'memory': '2560', 'ppl': '25'},
 {'fee': '180', 'memory': '3584', 'ppl': '35'},
 {'fee': '240', 'memory': '4608', 'ppl': '45'},
 {'fee': '270', 'memory': '5120', 'ppl': '50'},
 {'fee': '300', 'memory': '6144', 'ppl': '60'},
 {'fee': '360', 'memory': '7168', 'ppl': '70'},
 {'fee': '420', 'memory': '8192', 'ppl': '80'},
 {'fee': '480', 'memory': '10240', 'ppl': '100'}
]


api = multicraftapi .getapi()

class CCSheetError(Exception): pass
class EMCError(CCSheetError): pass
class EServerMotFoundInMC(EMCError): pass
class EServerCreateError(EMCError): pass
class EServerUpdateError(EMCError): pass
class EServerSuspendError(EMCError): pass
class EServerRemoveError(EMCError): pass
class EServerCantRemove(EServerRemoveError): pass
class EServerOnline(EServerRemoveError): pass
class ESheetError(CCSheetError): pass
class ESheetServerExists(ESheetError): pass
class ESheetServerNotExists(ESheetError): pass


class CCSheet(object):
    def __init__(self, leveldb):
        self.db = leveldb

    def _put(self, serverid, res):
        return self.db.put(serverid, msgpack.packb(res))

    def _get(self, serverid):
        res = self.db.get(serverid)
        if not res:
            raise ESheetServerNotExists("该服务端ID不存在")
        return msgpack.unpackb(res, **UNPACKPARAM)

    def _get_multicraft_id(self, serverid):
        info = self._get(serverid)
        if "_multicraft_id" in info:
            return info["_multicraft_id"]
        else:
            find = api('findServers',['name'],[serverid])
            if find['data']['Servers']:
                for sid, name in find['data']['Servers'].iteritems():
                    if name.find(info["qq"]) != -1:
                        return sid
            raise EServerMotFoundInMC()
            


    def _get_config(self, serverid, cfgforupdate = False):
        info = self._get(serverid)
        svrmem = info["memory"]
        svrname = serverid + "-" + info["qq"]
        svrplayers = info["ppl"]
        svrport = info["port"]

        if not cfgforupdate:
            server = {u'announce_save': u'1',
                       u'autosave': u'1',
                       u'autostart': u'0',
                       u'daemon_id': u'6',
                       u'default_level': u'10',
                       # u'dir': u'server100',
                       # u'id': u'100',
                       u'ip': u'0.0.0.0',
                       u'jardir': u'server_base',
                       u'jarfile': u'craftbukkit-gbk.jar',
                       u'kick_delay': u'3000',
                       u'memory': u'%s' % svrmem,
                       u'name': svrname,
                       u'players': svrplayers,
                       u'port': svrport,
                       u'start_memory': u'64',
                       u'suspended': u'0',
                       u'world': u'world'}
            config = {u'chat_role': u'user',
                     u'display_ip': u'server5-temp.chinacraft.cc',
                     u'give_role': u'mod',
                     u'ip_auth_role': u'guest',
                     # u'server_id': u'100',
                     u'summon_role': u'mod',
                     u'tp_role': u'mod',
                     u'user_ftp': u'1',
                     u'user_jar': u'1',
                     u'user_mysql': u'1',
                     u'user_name': u'0',
                     u'user_players': u'0',
                     u'user_schedule': u'1',
                     u'user_visibility': u'0',
                     u'visible': u'2'}
            return (server, config)
        else:
            server = {
               u'memory': u'%s' % svrmem,
               u'name': svrname,
               u'players': svrplayers,
               u'port': svrport
            }
            return server

    def _raise(self, res, error):
        if res["errors"]:
            loo.error("发生错误! 原因: " + str(res["errors"]))
            loo.error(str(error))
            raise error
        else:
            return res

    def register(self, serverid, qq, cfgtype, port, username, password, comment = "", force = False):
        if isinstance(cfgtype, dict):
            tmp = {}
            for x in ["ppl", "fee", "memory"]:
                if x not in cfgtype:
                    raise ValueError("配置信息缺少了 {}, 请修正.".format(x))
                else:
                    tmp[x] = cfgtype[x]
            cfgtype = tmp
        elif isinstance(cfgtype, int):
            cfgtype = CFGTABLE[cfgtype]
        else:
            raise TypeError(u"配置类型(cfgtype) 类型错误 可接受类型为int. 现在该参数类型为 " + type(cfgtype))
        for x in [("username", "用户名"), ("password", "密码"), ("serverid", "服务器ID"), ("qq", "QQ")]:
            if not isinstance(locals()[svrid], (str, unicode)):
                raise TypeError("{name}({argname})类型不符合. 可接受类型为str, unicode. 现在该参数类型为 {type}".format(
                    type=type(locals()[svrid])), name=svrid, argname=svrid)
        res = {
            "_": serverid,
            "qq": qq,
            "username": username,
            "password": password,
            "port": port
        }
        res.update(cfgtype)
        oldserver = self.db.get(serverid)

        if not oldserver or (oldserver and force):
            self.db.put(serverid, msgpack.packb(res))
            loo.info("新服务器注册: {_}-{qq} {ppl}人{fee}元{memory}M 端口号 {port}".format(**res))
        else:
            raise RuntimeError("注册信息时错误! 该服务器ID已存在. 如果需要覆盖, 加force参数为True")

        return res

    def purge(self, serverid):
        loo.info("清除服务器ID为 {} 的信息.".format(serverid))
        return self.db.delete(serverid)

    def create(self, serverid):
        loo.info("尝试创建服务器")
        try:
            self._get_multicraft_id(serverid)
            raise EServerCreateError("所指定其服务器ID的服务器已存在.")
        except EServerMotFoundInMC, e:
            pass
        svrid = api("createServer")
        self._raise(
            svrid,
            EServerCreateError("创建服务器ID为 {} 的服务器发生错误".format(svrid))
        )
        svrid = svrid["data"]["id"]
        loo.info("创建服务器(ID: {})完成.".format(svrid))
        config = self._get_config(serverid)
        server = config[0]
        config = config[1]

        self._raise(
            api('updateServer',svrid,server.keys(),server.values()),
            EServerUpdateError("更新服务器%r信息错误." % serverid)
        )

        self._raise(
            api('updateServerConfig',svrid,config.keys(),config.values()),
            EServerUpdateError("更新服务器%r信息错误." % serverid)
        )
        loo.info("服务器(ID: {})配置已更新".format(svrid))

        info = self._get(serverid)
        info["_multicraft_id"] = svrid
        self._put(serverid, info)

        return self.update(serverid)

    def update(self, serverid):
        server = self._get_config(serverid, True)
        svrid = self._get_multicraft_id(serverid)
        info = self._get(serverid)
        self._raise(
            api('updateServer',svrid,server.keys(),server.values()),
            EServerUpdateError("更新服务器%r信息错误." % serverid)
        )
        usrexist = api.findUsers(['name'],[info["username"]])
        self._raise(
            usrexist,
            EServerUpdateError()
        )
        usrexist = usrexist["data"]
        if not ('Users' in usrexist and usrexist['Users']):
            usrid = api('createUser',info["username"],
                ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(16)) + \
                 info["qq"] + "@chinacraft.cc",info["password"])
            self._raise(
                usrid,
                EServerUpdateError()
            )
            usrid = usrid['data']['id']
        else:
            for uid, v in usrexist['Users'].iteritems():
                if htmltool.unescape(v) == info["username"]:
                    loo.info(u'发现已有用户名与配置用户名符合. %s' % usrexist)
                    usrid = uid
                    break
        loo.info( "用户编号: %r, 服务器编号: %r" % (usrid,svrid) )
        loo.info( u'用户建立完成. 编号: %r 用户: %r' % (usrid,info["username"]) )
        self._raise( api('setServerOwner',svrid,usrid), EServerUpdateError())
        self._raise( api('setUserFtpAccess',usrid,svrid,"rw"), EServerUpdateError())
        loo.info( u'配置FTP权限完成.' )
        loo.info( u'服务器%r 已经配置完成.' % server["name"] )

    def remove(self, serverid):
        smcid = self._get_multicraft_id(serverid)
        status = api.getServerStatus(svrid)
        self._raise(
            status,
            EServerRemoveError("无法获得服务器(%s)状态" % serverid)
        )
        if status["data"]["status"] != 'offline':
            raise EServerOnline("请关闭服务器后,再来删除服务器")
        self._raise( api.deleteServer(smcid, "yes")
            ,EServerCantRemove("无法删除服务器"))

    def remove_(self, serverid):
        info = self._get(serverid)
        svrid = self._get_multicraft_id(serverid)
        oldusr = api('getServerOwner',svrid)['data']['user_id']
        if oldusr != u'0':
          oldusrname = api('getUser',oldusr)['data']['User']['name']
          oldsvr = api.listServersByOwner(oldusr)['data']['Servers']
          if int(oldusr): # oldusr -> int(oldusr) = 0
            print "旧服务器用户编号:",oldusr
            print "旧服务器用户删除:",api('deleteUser',oldusr) \
              if len(oldsvr) <= 1 else "旧服务器用户拥有着%d台服务器. %r" % (len(oldsvr),oldsvr)
        while 0 if api.getServerStatus(svrid)['data']['status'] == 'offline' else 1:
          stop = api.stopServer(svrid)
          print "\r正在停止服务器中... %r" % stop
          time.sleep(1)
        else:
          stop = api.stopServer(svrid)
        while api.getServerStatus(svrid)['success']:
          print "旧服务器删除操作:",api('deleteServer',svrid,"yes") if stop['success'] else "无法停止旧服务器 %r" % stop

    def suspend(self, serverid):
        self._raise(
            api.suspendServer(self._get_multicraft_id(serverid)),
            EServerSuspendError("停用服务器出错")
        )

    def check_list_diff(self):
        raise NotImplementedError()

def get_db():
    return plyvel.DB('./serverdb', create_if_missing=True)

def main():
    global loo
    logger = logging.getLogger('root')
    logger.setLevel(logging.DEBUG)
    fh = logging.FileHandler('CCSheet.log')
    fh.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s %(message)s')
    fh.setFormatter(formatter)
    ch.setFormatter(formatter)
    logger.addHandler(fh)
    logger.addHandler(ch)
    loo = logger
    db = get_db()
    sheet = CCSheet(db)
    customcfg = {'fee': '100', 'memory': '1536', 'ppl': '15'}
    serverid = "S5TMC15"
    reginfo = {
        "serverid": serverid,
        "qq": "",
        "cfgtype": 0,
        "port": "12516",
        "username": "",
        "password": "",
        "comment": "",
        # "force": True
    }
    # sheet.register(**reginfo)
    # sheet.create(serverid)
    # sheet.update(serverid)
    sheet.remove_(serverid)


if __name__ == '__main__':
    main()
```

if you don't understand now, welcome feedback.

**Comment by mindcat** [comment]
And if you want put your multicraft api key in python script file, find:
```python
def getapi():
# multicraftapi(apiurl, username, apikey)
    return  multicraftapi('http://example.com/multicraft/api.php', 'demo', '57ce2b0285bd3c5568e0')
```
and modify it.

**Comment by mindcat** [comment]
Timeout for waiting respond, closing.
